name: Flutter_iOS

on:
  push:
    branches:
      - atul_branch
      - arvind_branchs
  pull_request:
    branches:
      - atul_branch
      - arvind_branchs

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'

      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign